apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka-rest.fullname" . }}
  labels:
    app: {{ template "kafka-rest.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  ports:
    - name: kafka-rest
      port: {{ .Values.service.port }}
  selector:
    app: {{ template "kafka-rest.name" . }}
    release: {{ .Release.Name | quote}}
