# Default values for schema-registry-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: confluentinc/cp-kafka-rest
  tag: 5.1.2
  pullPolicy: IfNotPresent

service:
  port: 8082
  annotations: {}
  ## Limit load balancer source ips to list of CIDRs (where available)
  # loadBalancerSourceRanges: []

restlisteners:
  url: "http://localhost"
  port: 8082

schemaregistry:
  url: http://kub-kafka-schema-registry.local:8081

zookeeper:
  zkHosts: localhost:2181

ingress:
  enabled: false
  annotations: {}
  path: /
  hostname: kafka-rest.local
  tls:
    enabled: false


configurationOverrides:
  access.control.allow.methods: GET,POST,PUT,OPTIONS
  access.control.allow.origin: '*'
resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
